### ISSUE TITLE
Bot Offline

### ISSUE THREAD

**Issue by fixel99** [Rain288/discord-bot#1]
Not sure if this project is still active, but the bot is offline for me so therefore it is unusable. I have been struggling to find a bot with a mass-move functionality, so it would be great if I could use this one!

**Comment by Rain288** [comment]
Yeah, I had to stop paying for my VPS since I had to use the money for something else so the bot is naturally offline... I should update the readme appropriately to point out it's no longer online, my bad!
However, you can host it yourself! Though if you have no experience with hosting bots it can be a tad of a hassle. Specifically you would need to:
* Have python3
* Run `pip install discord` to get the discord.py library for python
* Download this github repo as zip and extract it
* Edit bot.py with a text editor of your choice
* In the last line, where it says `'token here'`, **inside** the quotations replace the words `token here` with a token you can get by making a bot account [here](https://discordapp.com/developers/applications/me/create)
* Run bot.py
* Now visit this link `https://discordapp.com/oauth2/authorize?client_id=ID_HERE&scope=bot&permissions=0x0000010` and replace ID_HERE with the Bot ID you can find in the bot account section

Again, sorry for not having updated the description to inform that the bot is offline, and also sorry for it being offline, I know that these features don't exist in many bots (that's why I made this one!), but I can't host it for a bit. :|

**Comment by fixel99** [comment]
Well I appreciate the quick reply! Sucks that you can't host it but definitely understandable. Guess I'll give hosting it myself a go. Thanks for listing the steps/requirements :)
