### ISSUE TITLE
Could not find a version that satisfies the requirement discord

### ISSUE THREAD

**Issue by fixel99** [Rain288/discord-bot#2]
Hey again. Not sure if this is a python issue or something on the bots end but as after installing Python, navigating to the right directory in cmd and running pip install -r requirements.txt, I get an error: 

Could not find a version that satisfies the requirement discord (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for discord (from -r requirements.txt (line 1))

Any ideas?

**Comment by fixel99** [comment]
I changed discord to discord.py in requirements (Not sure if this is the same thing? But after looking at some other bots it looked right.) This ran a lot more lines, but now i'm stuck with:

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Fixel\AppData\Local\Temp\pip-build-85buo5g3\logging\

**Comment by Rain288** [comment]
Oh, yeah it should be discord.py and not discord, just since you do `import discord` after you install discord.py I thought maybe that's the library's name in PIP, my bad! I have it installed for months now so I forgot what the proper name was :P 

As for the second error, `Command "python setup.py egg_info" failed with error code 1`, I could be wrong but I think error code 1 is `Operation not permitted` so you should try running CMD as admin.
This error is related to PIP and not `requirements.txt` or my bot so it's Python-related.

Thanks for pointing out the discord -> discord.py problem though!

**Comment by fixel99** [comment]
Worked perfectly thank you!
